name = "snagd-web"
pages_build_output_dir = "./out"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "snagd-production"
database_id = "c98c80bc-9976-4a3c-b647-3fd4e646fa9c"
