name = "snagd-web-local"
pages_build_output_dir = "./out"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "snagd-production"
database_id = "00000000-0000-0000-0000-000000000000"
