const contentIdeas = ["Film a 30-second deal check before pickup", "Compare two listings and explain the stronger margin", "Show a VIN scan at a door jamb", "Share a weekly flip recap with real costs", "Build a niche watchlist on camera"];
const scripts = [
  { hook: "Before you drive across town...", body: "I run the listing through Snagd, check the margin and risks, then decide whether it is worth the pickup." },
  { hook: "This cheap car could still be expensive.", body: "I scan the VIN first, review Vehicle Intelligence, and only then work out my maximum offer." },
  { hook: "Three listings. One worth chasing.", body: "Here is how I filter by distance, profit target, condition, and score before messaging a seller." },
];

export function CreatorPlaybook() {
  return <section className="grid gap-4"><div><p className="text-sm font-bold text-brand">Creator Guide / Playbook</p><h2 className="mt-1 text-2xl font-bold text-ink">Make useful content that earns trust</h2><p className="mt-2 text-sm leading-6 text-muted">Demonstrate the workflow, show your judgment, and invite viewers to try the same tools with your code.</p></div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Content ideas" items={contentIdeas} /><Panel title="Showcase the product" items={["Start with the listing or vehicle", "Show the filter or scan action", "Explain one risk signal", "Show the decision, not a guaranteed outcome", "End with your referral code on screen"]} /></div><div className="grid gap-3">{scripts.map((script) => <article key={script.hook} className="rounded-card border border-line bg-surface-2 p-4"><p className="font-bold text-ink">“{script.hook}”</p><p className="mt-2 text-sm leading-6 text-muted">{script.body}</p><p className="mt-3 text-xs font-bold text-brand">CTA: “Try Snagd with my code and build your own buying checklist.”</p></article>)}</div><div className="grid gap-3 sm:grid-cols-2"><Panel title="UGC examples" items={["Screen recording with voiceover", "Door-jamb scan in a parking lot", "Talking-head deal breakdown", "Before/after profit recap", "Saved-search setup tutorial"]} /><Panel title="Keep it compliant" items={["Clearly disclose that you may earn a commission", "Use #ad or #affiliate where required", "Never guarantee profits or resale prices", "Describe estimates as decision support", "Share real costs and risks when discussing results"]} /></div><div className="rounded-[18px] border border-amber/35 bg-amber/10 p-4"><p className="font-bold text-amber">Disclosure reminder</p><p className="mt-1 text-sm leading-6 text-muted">Example: “I may earn a commission if you subscribe with my link. Results vary, and no tool can guarantee a profitable flip.”</p></div></section>;
}
function Panel({ title, items }: { title: string; items: string[] }) { return <div className="rounded-[18px] border border-line bg-surface p-4"><h3 className="font-bold text-ink">{title}</h3><ul className="mt-3 grid gap-2 text-sm text-muted">{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" /><span>{item}</span></li>)}</ul></div>; }
