"use client";

import { useState } from "react";
import { AppCard } from "@/components/app/AppCard";
import { CreatorPlaybook } from "@/components/creator/CreatorPlaybook";
import { currency, numberCompact } from "@/lib/format";
import type { CreatorStats } from "@/types/snagd";

export function CreatorDashboardClient({ stats }: { stats: CreatorStats }) {
  const [copied, setCopied] = useState("");
  async function copy(value: string, label: string) { await navigator.clipboard?.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1400); }
  const metrics = [["Clicks", numberCompact(stats.referralClicks)], ["Signups", numberCompact(stats.trialSignups)], ["Paid conversions", numberCompact(stats.paidSubscribers)], ["Active subscribers", numberCompact(stats.activeSubscribers)], ["Monthly commission", currency(stats.monthlyRecurringCommission)], ["Lifetime commission", currency(stats.lifetimeCommission)], ["Estimated payout", currency(stats.estimatedPayout)], ["Conversion rate", `${stats.conversionRate}%`]];
  return <div className="mx-auto grid max-w-shell gap-5"><AppCard className="brand-panel"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-brand">Creator Dashboard</p><h1 className="mt-1 text-3xl font-bold text-ink">30% recurring commission</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Earn while each referred subscriber remains active. Metrics below are sample dashboard data until referral tracking and payouts are connected.</p></div><span className="rounded-full border border-profit/30 bg-profit/10 px-3 py-1 text-xs font-bold text-profit">{stats.payoutStatus}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-[.7fr_1.3fr]"><CopyField label="Creator code" value={stats.creatorCode} copied={copied} onCopy={copy} /><CopyField label="Referral link" value={stats.referralLink} copied={copied} onCopy={copy} /></div></AppCard><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label, value]) => <AppCard key={label}><p className="text-xs text-muted">{label}</p><p className="mt-2 font-mono text-2xl font-bold text-brand">{value}</p></AppCard>)}</div><AppCard><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold text-ink">Payout placeholder</h2><p className="mt-1 text-sm text-muted">Next estimated payout: {stats.nextPayoutDate}</p></div><p className="font-mono text-2xl font-bold text-profit">{currency(stats.estimatedPayout)}</p></div></AppCard><CreatorPlaybook /></div>;
}
function CopyField({ label, value, copied, onCopy }: { label: string; value: string; copied: string; onCopy: (value: string, label: string) => void }) { return <div className="rounded-card border border-line bg-surface p-3"><p className="text-xs text-muted">{label}</p><div className="mt-1 flex items-center gap-2"><p className="min-w-0 flex-1 truncate font-mono text-sm font-bold text-ink">{value}</p><button type="button" onClick={() => void onCopy(value, label)} className="rounded-card border border-brand/30 bg-brand/10 px-3 py-2 text-xs font-bold text-brand">{copied === label ? "Copied" : "Copy"}</button></div></div>; }
