import type { Alert } from "@/types/snagd";

export const mockAlerts: Alert[] = [
  {
    id: "alert-new-good-deal",
    type: "New good deal found",
    item: "Leather sectional couch",
    score: 91,
    profit: "$100-$150",
    distance: "7 miles",
    timePosted: "12 min ago",
    why: "Score cleared your 75 minimum with low pickup distance and strong resale range.",
    severity: "profit",
  },
  {
    id: "alert-high-score",
    type: "High Snagd Score",
    item: "Milwaukee tool bundle",
    score: 84,
    profit: "$75-$120",
    distance: "12 miles",
    timePosted: "28 min ago",
    why: "Brand demand and bundle pricing suggest fast resale if tools test clean.",
    severity: "profit",
  },
  {
    id: "alert-underpriced",
    type: "Underpriced listing",
    item: "Breville espresso machine",
    score: 81,
    profit: "$55-$95",
    distance: "4 miles",
    timePosted: "3 hrs ago",
    why: "Asking price is below typical local resale range for working units.",
    severity: "info",
  },
  {
    id: "alert-seller-urgency",
    type: "Seller urgency detected",
    item: "Garage tool chest",
    score: 73,
    profit: "$60-$100",
    distance: "10 miles",
    timePosted: "44 min ago",
    why: "Copy suggests quick pickup preference. Confirm condition before offering.",
    severity: "amber",
  },
  {
    id: "alert-price-drop",
    type: "Price drop",
    item: "Dining table set",
    score: 69,
    profit: "$45-$80",
    distance: "6 miles",
    timePosted: "1 hr ago",
    why: "Price dropped 25% since the first source-layer snapshot.",
    severity: "amber",
  },
  {
    id: "alert-free-item",
    type: "Free item with resale potential",
    item: "Free dresser",
    score: 78,
    profit: "$45-$90",
    distance: "9 miles",
    timePosted: "1 hr ago",
    why: "Free inventory can work, but pickup space and cleaning time matter.",
    severity: "profit",
  },
  {
    id: "alert-low-competition",
    type: "Low competition opportunity",
    item: "Commercial wire shelving",
    score: 74,
    profit: "$70-$130",
    distance: "15 miles",
    timePosted: "2 hrs ago",
    why: "Niche buyer demand is steady and the listing title is underspecified.",
    severity: "info",
  },
  {
    id: "alert-risk-warning",
    type: "Risk warning",
    item: "iPhone 12 cracked screen",
    score: 58,
    profit: "$10-$55",
    distance: "5 miles",
    timePosted: "41 min ago",
    why: "Thin margin after repair risk. Verify activation lock, carrier, and parts cost.",
    severity: "risk",
  },
  {
    id: "alert-likely-gone",
    type: "Deal likely gone",
    item: "Nintendo Switch bundle",
    score: 88,
    profit: "$80-$120",
    distance: "3 miles",
    timePosted: "4 hrs ago",
    why: "High score item has aged past your fast-flip response window.",
    severity: "risk",
  },
];
