import type { Deal } from "@/types/snagd";

export const mockDeals: Deal[] = [
  {
    id: "deal-leather-sectional",
    itemName: "Leather sectional couch",
    askingPrice: 90,
    askingLabel: "$90",
    estimatedResale: "$220-$280",
    estimatedResaleLow: 220,
    estimatedResaleHigh: 280,
    estimatedProfit: "$100-$150",
    estimatedProfitLow: 100,
    estimatedProfitHigh: 150,
    score: 91,
    recommendation: "BUY",
    distance: "7 miles",
    distanceMiles: 7,
    risk: "Low",
    source: "Local listing placeholder",
    category: "Furniture",
    condition: "Good",
    timePosted: "12 min ago",
    reason: "Low buy price, clean photos, strong local resale demand, and short pickup distance.",
  },
  {
    id: "deal-milwaukee-tools",
    itemName: "Milwaukee tool bundle",
    askingPrice: 140,
    askingLabel: "$140",
    estimatedResale: "$240-$300",
    estimatedResaleLow: 240,
    estimatedResaleHigh: 300,
    estimatedProfit: "$75-$120",
    estimatedProfitLow: 75,
    estimatedProfitHigh: 120,
    score: 84,
    recommendation: "BUY",
    distance: "12 miles",
    distanceMiles: 12,
    risk: "Medium",
    source: "Manual source layer",
    category: "Tools",
    condition: "Good",
    timePosted: "28 min ago",
    reason: "Recognizable brand bundle with enough margin after pickup and basic testing.",
  },
  {
    id: "deal-iphone-12",
    itemName: "iPhone 12 cracked screen",
    askingPrice: 180,
    askingLabel: "$180",
    estimatedResale: "$220-$280",
    estimatedResaleLow: 220,
    estimatedResaleHigh: 280,
    estimatedProfit: "$10-$55",
    estimatedProfitLow: 10,
    estimatedProfitHigh: 55,
    score: 58,
    recommendation: "MAYBE",
    distance: "5 miles",
    distanceMiles: 5,
    risk: "High",
    source: "User supplied listing",
    category: "Electronics",
    condition: "Damaged",
    timePosted: "41 min ago",
    reason: "Repair uncertainty and activation risk leave only a thin profit window.",
  },
  {
    id: "deal-free-dresser",
    itemName: "Free dresser",
    askingPrice: 0,
    askingLabel: "Free",
    estimatedResale: "$60-$120",
    estimatedResaleLow: 60,
    estimatedResaleHigh: 120,
    estimatedProfit: "$45-$90",
    estimatedProfitLow: 45,
    estimatedProfitHigh: 90,
    score: 78,
    recommendation: "BUY",
    distance: "9 miles",
    distanceMiles: 9,
    risk: "Medium",
    source: "Local listing placeholder",
    category: "Furniture",
    condition: "Fair",
    timePosted: "1 hr ago",
    reason: "Free inventory with resale upside if pickup space and cleaning time are available.",
    note: "Needs pickup space and possible cleaning.",
  },
  {
    id: "deal-honda-civic",
    itemName: "2012 Honda Civic",
    askingPrice: 2400,
    askingLabel: "$2,400",
    estimatedResale: "$3,400-$4,200",
    estimatedResaleLow: 3400,
    estimatedResaleHigh: 4200,
    estimatedProfit: "$550-$1,100",
    estimatedProfitLow: 550,
    estimatedProfitHigh: 1100,
    score: 76,
    recommendation: "MAYBE",
    distance: "18 miles",
    distanceMiles: 18,
    risk: "High",
    source: "Vehicle source placeholder",
    category: "Vehicle",
    condition: "Runs and drives",
    timePosted: "2 hrs ago",
    reason: "Possible upside, but title, history, mileage, and repair checks decide the buy.",
    note: "Vehicle Mode requires VIN/title/history checks before buying.",
  },
  {
    id: "deal-espresso-machine",
    itemName: "Breville espresso machine",
    askingPrice: 110,
    askingLabel: "$110",
    estimatedResale: "$190-$240",
    estimatedResaleLow: 190,
    estimatedResaleHigh: 240,
    estimatedProfit: "$55-$95",
    estimatedProfitLow: 55,
    estimatedProfitHigh: 95,
    score: 81,
    recommendation: "BUY",
    distance: "4 miles",
    distanceMiles: 4,
    risk: "Medium",
    source: "Manual source layer",
    category: "Appliances",
    condition: "Good",
    timePosted: "3 hrs ago",
    reason: "Compact item, proven demand, and manageable testing checklist.",
  },
];

export const bestDealToday = mockDeals[0];