import type { Deal, SimilarSale } from "@/types/snagd";

const marketplaceUrl = "https://www.facebook.com/marketplace/";

export const similarSales: SimilarSale[] = [
  { id: "sale-camry-1", itemTitle: "2021 Toyota Camry XLE clean title", thumbnailTone: "blue", price: 25400, condition: "Very Good", source: "Local sold comp", date: "Jun 27", matchConfidence: "High", notes: "Similar mileage and trim in the same metro." },
  { id: "sale-camry-2", itemTitle: "2020 Toyota Camry SE", thumbnailTone: "blue", price: 23100, condition: "Good", source: "Local sold comp", date: "Jun 22", matchConfidence: "High", notes: "Higher miles, sold quickly after price drop." },
  { id: "sale-ps5-1", itemTitle: "PlayStation 5 Disc with controller", thumbnailTone: "blue", price: 480, condition: "Like new", source: "Local sold comp", date: "Jun 28", matchConfidence: "High", notes: "Complete console bundles moved fast." },
  { id: "sale-tools-1", itemTitle: "Milwaukee M18 drill and impact bundle", thumbnailTone: "amber", price: 285, condition: "Good", source: "Local sold comp", date: "Jun 28", matchConfidence: "High", notes: "Battery count drove final price." },
  { id: "sale-sectional-1", itemTitle: "Brown leather sectional, clean", thumbnailTone: "blue", price: 260, condition: "Good", source: "Local sold comp", date: "Jun 26", matchConfidence: "High", notes: "Similar size, fast local pickup." },
  { id: "sale-phone-1", itemTitle: "iPhone 12 cracked but unlocked", thumbnailTone: "red", price: 245, condition: "Damaged", source: "Local sold comp", date: "Jun 19", matchConfidence: "Medium", notes: "Repair cost varied by buyer." },
];

function salesFor(kind: string) {
  if (kind === "vehicle") return [similarSales[0], similarSales[1], similarSales[3]];
  if (kind === "console") return [similarSales[2], similarSales[3], similarSales[5]];
  if (kind === "tools") return [similarSales[3], similarSales[4], similarSales[2]];
  if (kind === "phone") return [similarSales[5], similarSales[2], similarSales[3]];
  return [similarSales[4], similarSales[3], similarSales[2]];
}

export const mockDeals: Deal[] = [
  {
    id: "deal-2021-toyota-camry-xle",
    itemName: "2021 Toyota Camry XLE",
    thumbnailTone: "blue",
    sellerRating: "4.8 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 18900,
    askingLabel: "$18,900",
    estimatedResale: "$24,200-$26,600",
    estimatedResaleLow: 24200,
    estimatedResaleHigh: 26600,
    estimatedProfit: "$5,200-$6,500",
    estimatedProfitLow: 5200,
    estimatedProfitHigh: 6500,
    score: 91,
    recommendation: "BUY",
    distance: "3.2 miles",
    distanceMiles: 3.2,
    risk: "Low",
    source: "Facebook Marketplace seed",
    category: "Vehicle",
    vehicleYear: 2021,
    vehicleMake: "Toyota",
    vehicleModel: "Camry",
    vehicleMileage: 48200,
    cleanTitle: true,
    vinChecked: true,
    auctionHistorySignals: true,
    condition: "Very Good",
    timePosted: "12 min ago",
    reason: "Clean-title sedan, strong trim demand, and asking price well below nearby private-party comps.",
    similarSalesCount: 42,
    underMarketPercent: 32,
    demand: "High",
    competition: "Low",
    confidence: "High",
    reasonTags: ["Under market by 32%", "Based on 42 similar sales", "High resale demand", "Listed 12 minutes ago", "Low competition", "Clean title", "Strong margin"],
    similarSales: salesFor("vehicle"),
  },
  {
    id: "deal-playstation-5-disc",
    itemName: "PlayStation 5 Disc console",
    thumbnailTone: "blue",
    sellerRating: "4.9 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 340,
    askingLabel: "$340",
    estimatedResale: "$460-$520",
    estimatedResaleLow: 460,
    estimatedResaleHigh: 520,
    estimatedProfit: "$110-$140",
    estimatedProfitLow: 110,
    estimatedProfitHigh: 140,
    score: 86,
    recommendation: "BUY",
    distance: "2.1 miles",
    distanceMiles: 2.1,
    risk: "Low",
    source: "Facebook Marketplace seed",
    category: "Electronics",
    priceDropped: true,
    condition: "Like new",
    timePosted: "28 min ago",
    reason: "Complete disc console bundle with clean photos and enough spread after pickup and platform fees.",
    similarSalesCount: 38,
    underMarketPercent: 18,
    demand: "High",
    competition: "Medium",
    confidence: "High",
    reasonTags: ["Under market by 18%", "Price drop", "Fast sell-through", "High demand", "Ask for serial photo", "Strong margin"],
    similarSales: salesFor("console"),
  },
  {
    id: "deal-milwaukee-m18-bundle",
    itemName: "Milwaukee M18 tool bundle",
    thumbnailTone: "amber",
    sellerRating: "New seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 140,
    askingLabel: "$140",
    estimatedResale: "$240-$300",
    estimatedResaleLow: 240,
    estimatedResaleHigh: 300,
    estimatedProfit: "$75-$120",
    estimatedProfitLow: 75,
    estimatedProfitHigh: 120,
    score: 84,
    recommendation: "BUY",
    distance: "12 miles",
    distanceMiles: 12,
    risk: "Medium",
    source: "Facebook Marketplace seed",
    category: "Tools",
    condition: "Good",
    timePosted: "34 min ago",
    reason: "Recognizable brand bundle with enough margin after pickup and battery testing.",
    similarSalesCount: 31,
    underMarketPercent: 26,
    demand: "High",
    competition: "Medium",
    confidence: "High",
    reasonTags: ["Under market by 26%", "Based on 31 similar sales", "Seller wants quick pickup", "Test batteries", "Strong margin"],
    similarSales: salesFor("tools"),
  },
  {
    id: "deal-leather-sectional",
    itemName: "Leather sectional couch",
    thumbnailTone: "blue",
    sellerRating: "4.8 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 90,
    askingLabel: "$90",
    estimatedResale: "$220-$280",
    estimatedResaleLow: 220,
    estimatedResaleHigh: 280,
    estimatedProfit: "$100-$150",
    estimatedProfitLow: 100,
    estimatedProfitHigh: 150,
    score: 82,
    recommendation: "BUY",
    distance: "7 miles",
    distanceMiles: 7,
    risk: "Low",
    source: "Facebook Marketplace seed",
    category: "Furniture",
    condition: "Good",
    timePosted: "44 min ago",
    reason: "Low buy price, clean photos, strong local resale demand, and short pickup distance.",
    similarSalesCount: 42,
    underMarketPercent: 32,
    demand: "High",
    competition: "Low",
    confidence: "High",
    reasonTags: ["Under market by 32%", "Based on 42 similar sales", "High resale demand", "Low competition", "Minor wear only"],
    similarSales: salesFor("furniture"),
  },
  {
    id: "deal-free-dresser",
    itemName: "Free six-drawer dresser",
    thumbnailTone: "blue",
    sellerRating: "4.9 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 0,
    askingLabel: "Free",
    estimatedResale: "$60-$120",
    estimatedResaleLow: 60,
    estimatedResaleHigh: 120,
    estimatedProfit: "$45-$90",
    estimatedProfitLow: 45,
    estimatedProfitHigh: 90,
    score: 78,
    recommendation: "BUY",
    distance: "9 miles",
    distanceMiles: 9,
    risk: "Medium",
    source: "Facebook Marketplace seed",
    category: "Furniture",
    condition: "Fair",
    timePosted: "1 hr ago",
    reason: "Free inventory with resale upside if pickup space and cleaning time are available.",
    note: "Needs pickup space and basic cleaning.",
    similarSalesCount: 24,
    underMarketPercent: 100,
    demand: "Medium",
    competition: "Low",
    confidence: "Medium",
    reasonTags: ["Under market by 100%", "Free item with resale potential", "Needs pickup space", "Cleaning likely", "Low competition"],
    similarSales: salesFor("furniture"),
  },
  {
    id: "deal-honda-civic",
    itemName: "2012 Honda Civic LX",
    thumbnailTone: "blue",
    sellerRating: "4.7 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 2400,
    askingLabel: "$2,400",
    estimatedResale: "$3,400-$4,200",
    estimatedResaleLow: 3400,
    estimatedResaleHigh: 4200,
    estimatedProfit: "$550-$1,100",
    estimatedProfitLow: 550,
    estimatedProfitHigh: 1100,
    score: 76,
    recommendation: "MAYBE",
    distance: "18 miles",
    distanceMiles: 18,
    risk: "High",
    source: "Facebook Marketplace seed",
    category: "Vehicle",
    vehicleYear: 2012,
    vehicleMake: "Honda",
    vehicleModel: "Civic",
    vehicleMileage: 168000,
    cleanTitle: false,
    vinChecked: false,
    auctionHistorySignals: false,
    condition: "Runs and drives",
    timePosted: "2 hrs ago",
    reason: "Possible upside, but title, history, mileage, and repair checks decide the buy.",
    note: "Run VIN, title, and history checks before making an offer.",
    similarSalesCount: 15,
    underMarketPercent: 22,
    demand: "High",
    competition: "Medium",
    confidence: "Medium",
    reasonTags: ["Under market by 22%", "Vehicle check required", "Title/history risk", "Repair cost unknown"],
    similarSales: salesFor("vehicle"),
  },
  {
    id: "deal-breville-barista-express",
    itemName: "Breville Barista Express",
    thumbnailTone: "blue",
    sellerRating: "4.9 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 110,
    askingLabel: "$110",
    estimatedResale: "$190-$240",
    estimatedResaleLow: 190,
    estimatedResaleHigh: 240,
    estimatedProfit: "$55-$95",
    estimatedProfitLow: 55,
    estimatedProfitHigh: 95,
    score: 81,
    recommendation: "BUY",
    distance: "4 miles",
    distanceMiles: 4,
    risk: "Medium",
    source: "Facebook Marketplace seed",
    category: "Appliances",
    condition: "Good",
    timePosted: "3 hrs ago",
    reason: "Compact item, proven demand, and manageable testing checklist.",
    similarSalesCount: 28,
    underMarketPercent: 24,
    demand: "High",
    competition: "Medium",
    confidence: "High",
    reasonTags: ["Under market by 24%", "Fast sell-through", "Based on 28 similar sales", "Test pump pressure"],
    similarSales: salesFor("tools"),
  },
  {
    id: "deal-iphone-12-cracked",
    itemName: "iPhone 12 cracked screen",
    thumbnailTone: "red",
    sellerRating: "4.6 seller",
    listingUrl: marketplaceUrl,
    messageUrl: marketplaceUrl,
    askingPrice: 180,
    askingLabel: "$180",
    estimatedResale: "$220-$280",
    estimatedResaleLow: 220,
    estimatedResaleHigh: 280,
    estimatedProfit: "$10-$55",
    estimatedProfitLow: 10,
    estimatedProfitHigh: 55,
    score: 58,
    recommendation: "MAYBE",
    distance: "5 miles",
    distanceMiles: 5,
    risk: "High",
    source: "Facebook Marketplace seed",
    category: "Electronics",
    condition: "Damaged",
    timePosted: "41 min ago",
    reason: "Repair uncertainty and activation risk leave only a thin profit window.",
    similarSalesCount: 18,
    underMarketPercent: 9,
    demand: "Medium",
    competition: "High",
    confidence: "Medium",
    reasonTags: ["Under market by 9%", "Risk: repair cost unknown", "Thin margin", "Verify activation lock"],
    similarSales: salesFor("phone"),
  },
];

export const bestDealToday = mockDeals[0];
export const savedDealSeeds = [mockDeals[0], mockDeals[1], mockDeals[4]];
