import type { Watchlist } from "@/types/snagd";

export const nichePresets = [
  "Furniture flipper",
  "Electronics flipper",
  "Tool flipper",
  "Sneaker/clothing reseller",
  "Video game reseller",
  "Appliance reseller",
  "Car parts reseller",
  "Vehicle flipper",
  "Free item hunter",
  "Garage sale hunter",
  "Everything profitable",
  "High-ticket only",
  "Fast flips only",
] as const;

export const mockWatchlists: Watchlist[] = [
  {
    id: "watch-everything-profitable",
    name: "Anything with $75+ profit",
    nichePreset: "Everything profitable",
    everythingMode: true,
    location: "Columbus, OH",
    radius: 25,
    maxPickupDistance: 18,
    category: "Any",
    includeKeywords: "clean, working, moving, bundle, free",
    excludeKeywords: "broken, parts only, smoke damage, missing title",
    maxBuyPrice: 500,
    minimumEstimatedProfit: 75,
    minimumSnagdScore: 76,
    conditionPreference: "Good or better",
    alertSpeedPreference: "Fast",
    notificationMethod: "Email + in-app",
  },
  {
    id: "watch-tools",
    name: "Tools under market",
    nichePreset: "Tool flipper",
    everythingMode: false,
    location: "43215",
    radius: 35,
    maxPickupDistance: 25,
    category: "Tools",
    includeKeywords: "Milwaukee, DeWalt, Makita, bundle, battery",
    excludeKeywords: "not working, clone, missing battery",
    maxBuyPrice: 300,
    minimumEstimatedProfit: 60,
    minimumSnagdScore: 72,
    conditionPreference: "Testable",
    alertSpeedPreference: "Instant",
    notificationMethod: "In-app",
  },
  {
    id: "watch-vehicle-starters",
    name: "Vehicle starter flips",
    nichePreset: "Vehicle flipper",
    everythingMode: false,
    location: "Columbus, OH",
    radius: 50,
    maxPickupDistance: 40,
    category: "Vehicles",
    includeKeywords: "runs, clean title, civic, corolla, accord, camry",
    excludeKeywords: "salvage, no title, mechanic special, overheating",
    maxBuyPrice: 3500,
    minimumEstimatedProfit: 500,
    minimumSnagdScore: 70,
    conditionPreference: "Runs and drives",
    alertSpeedPreference: "Standard",
    notificationMethod: "Email + in-app",
  },
];