"use client";

import Link from "next/link";
/* eslint-disable @next/next/no-img-element -- crawler image hosts are dynamic in the static export. */
import { useEffect, useState } from "react";
import { AppCard } from "@/components/app/AppCard";
import { thumbnailClass } from "@/components/app/DealCard";
import { readJson, writeJson } from "@/lib/storage/snagdStorage";
import { crawlerApiClient } from "@/lib/services/crawlerApiClient";
import type { Deal, DealStatus, SimilarSale } from "@/types/snagd";

const savedKey = "snagd-saved-deal-ids";
const statusKey = "snagd-deal-statuses";
const dealStatuses: DealStatus[] = ["New", "Saved", "Messaged Seller", "Planning Pickup", "Bought", "Passed", "Lost / Sold to Someone Else", "Listed for Resale", "Sold"];

export function DealDetailClient({ deal }: { deal: Deal }) {
  const [savedIds, setSavedIds] = useState<string[]>([]);
  const [statuses, setStatuses] = useState<Record<string, DealStatus>>({});
  const [feedback, setFeedback] = useState("");
  const [showAllSales, setShowAllSales] = useState(false);
  const [trackingOpen, setTrackingOpen] = useState(false);
  useEffect(() => { setSavedIds(readJson(savedKey, [])); setStatuses(readJson(statusKey, {})); if (window.location.hash === "#track-outcome") setTrackingOpen(true); if (window.location.hash === "#similar-sales") setShowAllSales(true); }, []);

  const saved = savedIds.includes(deal.id);
  const status = statuses[deal.id] ?? deal.status ?? "New";
  const resaleMid = Math.round((deal.estimatedResaleLow + deal.estimatedResaleHigh) / 2);
  const valueLabel = deal.underMarketPercent >= 25 ? "Steal" : deal.underMarketPercent >= 10 ? "Fair" : "Overpriced";
  const marker = Math.max(8, Math.min(88, 100 - deal.underMarketPercent));
  function pulse(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(""), 1700); }
  function toggleSaved() { const next = saved ? savedIds.filter((id) => id !== deal.id) : [...savedIds, deal.id]; setSavedIds(next); writeJson(savedKey, next); if (deal.dataOrigin === "crawler") void crawlerApiClient.updateListingStatus(deal.crawlerListingId || deal.id, saved ? "new" : "saved").catch(() => undefined); pulse(saved ? "Removed from saved" : "Saved deal"); }
  function setStatus(nextStatus: DealStatus) { const next = { ...statuses, [deal.id]: nextStatus }; setStatuses(next); writeJson(statusKey, next); pulse(`Marked ${nextStatus}`); }
  function openListing() { if (deal.listingUrl) window.open(deal.listingUrl, "_blank", "noopener,noreferrer"); else pulse("No source listing URL provided"); }
  function messageSeller() { if (deal.dataOrigin === "crawler") void crawlerApiClient.updateListingStatus(deal.crawlerListingId || deal.id, "contacted").catch(() => undefined); if (deal.messageUrl || deal.listingUrl) window.open(deal.messageUrl || deal.listingUrl, "_blank", "noopener,noreferrer"); else pulse("No direct message link provided"); }
  async function shareDeal() { const text = `${deal.itemName} - estimated profit ${deal.estimatedProfit}, Snagd Score ${deal.score}.`; const canShare = typeof navigator.share === "function"; if (canShare) await navigator.share({ title: deal.itemName, text, url: deal.listingUrl ?? window.location.href }); else await navigator.clipboard.writeText(text); pulse(canShare ? "Share opened" : "Copied share text"); }

  return <div className="mx-auto min-w-0 max-w-[430px] overflow-x-clip pb-8">
    <div className={`relative h-64 overflow-hidden rounded-[22px] border border-line ${thumbnailClass(deal.thumbnailTone)}`}>{deal.imageUrls?.[0] && <img src={deal.imageUrls[0]} alt={deal.itemName} className="absolute inset-0 h-full w-full object-cover" />}<Link href="/app/deal-feed/" className="absolute left-3 top-3 grid h-10 min-w-10 place-items-center rounded-full bg-black/45 px-3 text-sm font-bold text-white">Back</Link><span className="absolute bottom-3 left-3 rounded-full bg-brand px-3 py-1 text-xs font-bold text-white">{deal.recommendation === "BUY" ? "STEAL" : deal.recommendation}</span><span className="absolute bottom-3 right-3 rounded-full bg-profit px-3 py-1 text-xs font-bold text-white">{deal.estimatedProfit}</span></div>
    <div className="mt-4 min-w-0"><h1 className="break-words text-2xl font-bold text-ink">{deal.itemName}</h1><p className="mt-1 break-words text-sm text-muted">{deal.source} / Posted {deal.timePosted} / {deal.distance} / {deal.sellerRating ?? "seller rating unavailable"}</p></div>
    <div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Asking" value={deal.askingLabel} /><Metric label="Est. value" value={deal.estimatedResale} /><Metric label="Est. profit" value={deal.estimatedProfit} accent /></div>
    <AppCard className="mt-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm text-muted">Value meter</p><h2 className="mt-1 break-words text-lg font-bold text-ink">Estimated value: ${resaleMid.toLocaleString()}</h2></div><span className="shrink-0 rounded-full bg-brand/10 px-3 py-1 text-sm font-bold text-brand">{valueLabel}</span></div><div className="relative mt-5 h-3 rounded-full value-meter"><span className="absolute top-1/2 h-8 w-1 -translate-y-1/2 rounded-full bg-info shadow-card" style={{ left: `${marker}%` }} /></div><div className="mt-2 flex justify-between text-[11px] text-muted"><span>Overpriced</span><span>Fair</span><span>Under market</span></div><p className="mt-3 text-sm text-muted">{deal.dataOrigin === "crawler" ? `Calculated from the normalized listing, category fallback or configured comps, distance, and estimated costs. Verify condition before buying.` : `Estimated ${deal.underMarketPercent}% under market based on ${deal.similarSalesCount} demo similar sales.`}</p></AppCard>
    <AppCard className="mt-4 bg-gradient-to-r from-brand/14 to-surface"><div className="flex flex-col gap-4"><div className="min-w-0"><p className="text-sm text-muted">Snagd Score</p><p className="font-mono text-4xl font-bold text-brand">{deal.score}</p><p className="mt-1 break-words text-sm text-muted">{deal.similarSalesCount} similar sales / {deal.demand} demand / {deal.competition} competition / {deal.confidence} confidence</p></div><div className="self-start rounded-[14px] bg-brand px-5 py-3 text-center text-white"><p className="text-xl font-bold">{deal.recommendation}</p><p className="text-xs">action rating</p></div></div><div className="mt-4 flex flex-wrap gap-2">{deal.reasonTags.slice(0, 5).map((tag) => <span key={tag} className={`rounded-full border px-2.5 py-1 text-[11px] ${tagClass(tag)}`}>{tag}</span>)}</div></AppCard>
    <div className="mt-4 grid grid-cols-2 gap-3"><Info label="Demand" value={deal.demand} /><Info label="Competition" value={deal.competition} /><Info label="Status" value={status} /></div>
    <AppCard className="mt-4"><h2 className="font-bold text-ink">Profit Breakdown</h2><Break label="Est. resale mid" value={`$${resaleMid.toLocaleString()}`} /><Break label="Estimated costs" value={deal.estimatedCosts === undefined ? "-$18 to -$45" : `-$${Math.round(deal.estimatedCosts).toLocaleString()}`} /><Break label="Est. profit" value={deal.estimatedProfit} accent />{deal.suggestedMaxBuyPrice !== undefined && <Break label="Suggested max buy" value={`$${deal.suggestedMaxBuyPrice.toLocaleString()}`} accent />}</AppCard>
    {deal.suggestedSellerMessage && <AppCard className="mt-4"><h2 className="font-bold text-ink">Suggested First Message</h2><p className="mt-2 break-words text-sm leading-6 text-muted">{deal.suggestedSellerMessage}</p><button onClick={() => { void navigator.clipboard.writeText(deal.suggestedSellerMessage || "").then(() => pulse("Seller message copied")); }} className="mt-3 w-full rounded-[14px] border border-brand/35 bg-brand/10 px-3 py-3 text-sm font-bold text-brand">Copy message</button></AppCard>}
    <div id="similar-sales" className="scroll-mt-24"><AppCard className="mt-4"><div className="flex items-center justify-between gap-3"><h2 className="font-bold text-ink">Similar Sales</h2>{deal.similarSales.length > 3 && <button onClick={() => setShowAllSales((value) => !value)} className="text-sm font-bold text-brand">{showAllSales ? "Show less" : "View all"}</button>}</div><div className="mt-3 grid gap-2">{deal.similarSales.length ? (showAllSales ? deal.similarSales : deal.similarSales.slice(0, 3)).map((sale) => <SimilarSaleRow key={sale.id} sale={sale} />) : <p className="rounded-card border border-amber/30 bg-amber/10 p-3 text-sm text-muted">No sold comps are attached yet. Use Analyze Listing before making an offer.</p>}</div></AppCard></div>
    <AppCard className="mt-4"><h2 className="font-bold text-ink">Listing Actions</h2><div className="mt-3 grid grid-cols-2 gap-2"><Action primary onClick={messageSeller}>Message Seller</Action><Action onClick={openListing}>Open Listing</Action><Action onClick={toggleSaved}>{saved ? "Saved" : "Save"}</Action><Action onClick={shareDeal}>Share</Action></div>{deal.dataOrigin === "crawler" && <button onClick={() => { void crawlerApiClient.updateListingStatus(deal.crawlerListingId || deal.id, "ignored").then(() => pulse("Listing ignored")).catch(() => pulse("Could not update listing")); }} className="mt-2 w-full rounded-[14px] border border-line bg-surface-2 px-3 py-3 text-sm font-bold text-muted">Ignore listing</button>}<button onClick={() => setTrackingOpen((value) => !value)} className="mt-2 w-full rounded-[14px] border border-brand/35 bg-brand/10 px-3 py-3 text-sm font-bold text-brand">{trackingOpen ? "Close Tracking" : "Track Outcome"}</button></AppCard>
    <div id="track-outcome" className="scroll-mt-24">{trackingOpen && <TrackingPanel deal={deal} status={status} onStatus={setStatus} />}</div>
    {feedback && <p className="mt-3 rounded-card border border-brand/35 bg-brand/10 px-4 py-2 text-center text-sm font-bold text-brand motion-slide">{feedback}</p>}
  </div>;
}

function TrackingPanel({ deal, status, onStatus }: { deal: Deal; status: DealStatus; onStatus: (status: DealStatus) => void }) { const [localStatus, setLocalStatus] = useState(status); const [purchasePrice, setPurchasePrice] = useState(deal.askingPrice); const [pickupCost, setPickupCost] = useState(18); const [repairCost, setRepairCost] = useState(0); const [soldPrice, setSoldPrice] = useState(deal.estimatedResaleLow); const [sellingFees, setSellingFees] = useState(12); const profit = soldPrice - purchasePrice - pickupCost - repairCost - sellingFees; return <AppCard className="mt-4 motion-slide"><p className="text-sm text-muted">Deal Tracking</p><h3 className="mt-1 break-words text-xl font-bold text-ink">{deal.itemName}</h3><div className="mt-4 grid gap-3"><select className="min-w-0 rounded-card border border-line bg-surface-2 p-3 text-ink" value={localStatus} onChange={(event) => setLocalStatus(event.target.value as DealStatus)}>{dealStatuses.map((item) => <option key={item}>{item}</option>)}</select>{["Bought", "Sold", "Listed for Resale"].includes(localStatus) && <div className="grid gap-3"><Input label="Purchase price" value={purchasePrice} setValue={setPurchasePrice} /><Input label="Pickup cost" value={pickupCost} setValue={setPickupCost} /><Input label="Repair / cleaning" value={repairCost} setValue={setRepairCost} /></div>}{localStatus === "Sold" && <div className="grid gap-3"><Input label="Sold price" value={soldPrice} setValue={setSoldPrice} /><Input label="Selling fees" value={sellingFees} setValue={setSellingFees} /><div className="rounded-card border border-profit/30 bg-profit/10 p-3"><p className="text-xs text-muted">Real result</p><p className="mt-1 font-mono text-lg font-bold text-profit">${profit}</p></div></div>}<textarea className="min-h-[86px] min-w-0 rounded-card border border-line bg-surface-2 p-3 text-ink" placeholder="Notes, seller response, pickup plan, or sale details" /><button onClick={() => onStatus(localStatus)} className="h-11 rounded-card bg-brand px-4 text-sm font-bold text-white">Save status</button></div></AppCard>; }
function SimilarSaleRow({ sale }: { sale: SimilarSale }) { return <div className="min-w-0 rounded-card border border-line bg-surface-2 p-3"><div className="flex min-w-0 gap-3"><div className={`h-14 w-14 shrink-0 rounded-card ${thumbnailClass(sale.thumbnailTone)}`} /><div className="min-w-0"><p className="break-words font-bold text-ink">{sale.itemTitle}</p><p className="mt-1 break-words text-sm text-muted">${sale.price} / {sale.condition} / {sale.source} / {sale.date}</p><p className="mt-1 break-words text-xs text-muted">{sale.matchConfidence} confidence. {sale.notes}</p></div></div></div>; }
function Input({ label, value, setValue }: { label: string; value: number; setValue: (value: number) => void }) { return <label className="min-w-0"><span className="text-xs text-muted">{label}</span><input className="mt-1 w-full min-w-0 rounded-card border border-line bg-surface-2 p-3 text-ink" type="number" value={value} onChange={(event) => setValue(Number(event.target.value))} /></label>; }
function Action({ children, onClick, primary = false }: { children: React.ReactNode; onClick: () => void; primary?: boolean }) { return <button onClick={onClick} className={`min-w-0 rounded-[14px] px-3 py-3 text-sm font-bold ${primary ? "bg-brand text-white" : "border border-line bg-surface-2 text-ink"}`}>{children}</button>; }
function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="min-w-0 rounded-[14px] border border-line bg-surface p-3"><p className="text-xs text-muted">{label}</p><p className={`mt-1 break-words font-mono text-sm font-bold ${accent ? "text-profit" : "text-ink"}`}>{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-[14px] border border-line bg-surface p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 break-words font-bold text-ink">{value}</p></div>; }
function Break({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="mt-3 flex min-w-0 items-center justify-between gap-3 border-b border-line pb-2 last:border-b-0"><span className="min-w-0 text-sm text-muted">{label}</span><span className={`shrink-0 font-mono font-bold ${accent ? "text-profit" : "text-ink"}`}>{value}</span></div>; }
function tagClass(tag: string) { const lower = tag.toLowerCase(); if (lower.includes("risk") || lower.includes("repair") || lower.includes("unknown")) return "border-pass/25 bg-pass/10 text-pass"; if (tag.includes("%") || lower.includes("profit")) return "border-profit/25 bg-profit/10 text-profit"; if (lower.includes("listed") || lower.includes("fast")) return "border-amber/25 bg-amber/10 text-amber"; return "border-brand/25 bg-brand/10 text-brand"; }
